---
name: tasky_mobile_app
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=2.17.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  sample_data:
    git:
      url: git@github.com:iamEtornam/sample_data.git
  flutter_custom_dialog: ^1.3.0
  bot_toast: ^4.1.3
  the_apple_sign_in: ^1.1.1
  cupertino_icons: ^1.0.8
  dotted_border: ^2.1.0
  extended_image: ^9.1.0
  firebase_analytics: ^11.4.0
  firebase_auth: ^5.4.0
  firebase_core: ^3.10.0
  firebase_crashlytics: ^4.3.0
  firebase_messaging: ^15.2.0
  flutter_font_icons: ^2.2.7
  flutter_image_stack: ^0.0.7
  flutter_local_notifications: ^18.0.1
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.17
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.2
  image_cropper: ^8.1.0
  image_picker: ^1.1.2
  intl: ^0.20.1
  logger: ^2.5.0
  modal_bottom_sheet: ^3.0.0-pre
  strings: ^3.2.0
  supercharged: ^2.1.1
  textfield_tags: ^3.0.1
  time_ago_provider: ^4.2.0
  readmore: ^3.0.0
  in_app_review: ^2.0.10
  open_apps_settings: ^0.0.4
  package_info_plus: ^8.1.3
  url_launcher: ^6.3.1
  http_parser: ^4.1.2
  path: ^1.9.1
  file: ^7.0.1
  collection: ^1.19.1
  flutter_tawk: ^0.1.0

dependency_overrides:
  path_provider: ^2.1.5
  firebase_storage: ^12.4.0
  intl: ^0.20.1
  collection: ^1.19.1
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: launcher_icon
  ios: true
  image_path: assets/tasky_logo_bg.png
flutter:
  uses-material-design: true
  assets:
    - assets/
